site:
  name: nhavantuonglai
  site: 'https://nhavantuonglai.com'
  base: '/'
  trailingSlash: false

metadata:
  title:
    default: nhavantuonglai
    template: '%s | nhavantuonglai'
  description: "Viết là nuôi dưỡng niềm đam mê, chữ để ươm mầm điều yêu thích. Học và hoàn thiện kỹ năng mỗi ngày không mong gì hơn đó là điều duy nhất người ta nhớ để nhắc về."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: nhavantuonglai
    image:
      url: 'https://nhavantuonglai.com/image/cover/001-753.jpg'
      width: 600
      height: 407
    type: website
  twitter:
    handle: '@nhavantuonglai'
    site: '@nhavantuonglai'
    card: summary_large_image
    image:
      url: 'https://nhavantuonglai.com/image/cover/001-746.jpg'
    title: Văn hay trong hiện tại, chữ tốt ở tương lai.
    description: Viết là nuôi dưỡng niềm đam mê, chữ để ươm mầm điều yêu thích. Học và hoàn thiện kỹ năng mỗi ngày không mong gì hơn đó là điều duy nhất người ta nhớ để nhắc về.

i18n:
  language: vi
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 20

    post:
      isEnabled: true
      permalink: 'article/%slug%'
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'article'
      robots:
        index: true
    tag:
      isEnabled: true
      pathname: 'tags'
      robots:
        index: true

    isRelatedPostsEnabled: true
    relatedPostsCount: 12

ui:
  theme: 'system'

  tokens:
    default:
      fonts:
        sans: InterVariable
        serif: InterVariable
        heading: InterVariable
      colors:
        default: rgb(33 39 55)
        heading: rgb(234 237 243)
        muted: rgb(33 39 55 / 66%)
        bgPage: rgb(234 237 243)
        primary: rgb(255 114 94)
        secondary: rgb(255 114 94)
        accent: rgb(255 114 94)
    dark:
      fonts: {}
      colors:
        default: rgb(234 237 243)
        heading: rgb(33 39 55)
        muted: rgb(229 236 246 / 66%)
        bgPage: rgb(33 39 55)
        primary: rgb(255 114 94)
        secondary: rgb(255 114 94)
        accent: rgb(255 114 94)