site:
  name: nhavantuonglai
  site: "https://nhavantuonglai.com"
  base: "/"
  trailingSlash: false

metadata:
  title:
    default: nhavantuonglai
    template: "%s | nhavantuonglai"
  description: "Viết là nuôi dưỡng niềm đam mê, chữ để ươm mầm điều yêu thích. Học và hoàn thiện kỹ năng mỗi ngày không mong gì hơn đó là điều duy nhất người ta nhớ để nhắc về."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: nhavantuonglai
    type: website
    locale: vi_VN
    image:
      url: "https://banmaixanh.org/image/cover/001-053.jpg"
      width: 1200
      height: 630
      alt: "Viết là nuôi dưỡng niềm đam mê, chữ để ươm mầm điều yêu thích. Học và hoàn thiện kỹ năng mỗi ngày không mong gì hơn đó là điều duy nhất người ta nhớ để nhắc về."
  twitter:
    card: summary_large_image
    site: "@nhavantuonglai"
    creator: "@nhavantuonglai"
    image: "https://banmaixanh.org/image/cover/001-053.jpg"
    description: "Viết là nuôi dưỡng niềm đam mê, chữ để ươm mầm điều yêu thích. Học và hoàn thiện kỹ năng mỗi ngày không mong gì hơn đó là điều duy nhất người ta nhớ để nhắc về."

i18n:
  language: vi
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 20

    post:
      isEnabled: true
      permalink: "article/%slug%"
      robots:
        index: true

    list:
      isEnabled: true
      pathname: "article"
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: "tags"
      robots:
        index: true

    isRelatedPostsEnabled: true
    relatedPostsCount: 12

ui:
  theme: "system"

  tokens:
    default:
      colors:
        default: rgb(33 39 55)
        heading: rgb(248 243 240)
        muted: rgb(33 39 55 / 66%)
        bgPage: rgb(248 243 240)
        primary: rgb(255 114 94)
        secondary: rgb(255 114 94)
        accent: rgb(255 114 94)
    dark:
      fonts: {}
      colors:
        default: rgb(248 243 240)
        heading: rgb(33 39 55)
        muted: rgb(229 236 246 / 66%)
        bgPage: rgb(33 39 55)
        primary: rgb(255 114 94)
        secondary: rgb(255 114 94)
        accent: rgb(255 114 94)