site:
  name: nhavantuonglai
  site: 'https://nhavantuonglai.com'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId:

metadata:
    title: content="<trống, cần điền>"
    type: content="website"
    url: content="https://nhavantuonglai.com"
    image: content="<trống, cần điền>"

    image:url: content="<trống, cần điền>"
    image:secure_url: content="<trống, cần điền>"
    image:type: content="image/jpeg"
    image:width: content="1200"
    image:height: content="630"
    image:alt: content="<trống, cần điền>"

    twitter:image: content="<trống, cần điền>"
    twitter:card: content="<trống, cần điền>"
    twitter:title: content="<trống, cần điền>"
    twitter:description: content="<trống, cần điền>"

i18n:
  language: vi
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 10

    post:
      isEnabled: true
      permalink: 'article/%slug%'
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'article'
      robots:
        index: true
    tag:
      isEnabled: true
      pathname: 'tags'
      robots:
        index: true

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

ui:
  theme: 'system'

  tokens:
    default:
      fonts:
        sans: InterVariable
        serif: InterVariable
        heading: InterVariable
      colors:
        default: rgb(33 39 55)
        heading: rgb(234 237 243)
        muted: rgb(33 39 55 / 66%)
        bgPage: rgb(234 237 243)
        primary: rgb(255 114 94)
        secondary: rgb(255 114 94)
        accent: rgb(255 114 94)
    dark:
      fonts: {}
      colors:
        default: rgb(234 237 243)
        heading: rgb(33 39 55)
        muted: rgb(229 236 246 / 66%)
        bgPage: rgb(33 39 55)
        primary: rgb(255 114 94)
        secondary: rgb(255 114 94)
        accent: rgb(255 114 94)