site:
  name: nhavantuonglai
  site: "https://nhavantuonglai.com"
  base: "/"
  trailingSlash: false

metadata:
  title:
    default: nhavantuonglai
    template: "%s | nhavantuonglai"
  description: "Viết là nuôi dưỡng niềm đam mê, chữ để ươm mầm điều yêu thích. Học và hoàn thiện kỹ năng mỗi ngày không mong gì hơn đó là điều duy nhất người ta nhớ để nhắc về."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: nhavantuonglai
    type: website
    locale: vi_VN
    image:
      url: "https://images.pexels.com/photos/32839477/pexels-photo-32839477.jpeg"
      width: 1200
      height: 630
      alt: "Viết là nuôi dưỡng niềm đam mê, chữ để ươm mầm điều yêu thích. Học và hoàn thiện kỹ năng mỗi ngày không mong gì hơn đó là điều duy nhất người ta nhớ để nhắc về."
  twitter:
    card: summary_large_image
    site: "@nhavantuonglai"
    creator: "@nhavantuonglai"
    image: "https://images.pexels.com/photos/32839477/pexels-photo-32839477.jpeg"
    description: "Viết là nuôi dưỡng niềm đam mê, chữ để ươm mầm điều yêu thích. Học và hoàn thiện kỹ năng mỗi ngày không mong gì hơn đó là điều duy nhất người ta nhớ để nhắc về."

i18n:
  language: vi
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 20
    post:
      isEnabled: true
      permalink: "article/%slug%"
      robots:
        index: true
    list:
      isEnabled: true
      pathname: "article"
      robots:
        index: true
    tag:
      isEnabled: true
      pathname: "tags"
      robots:
        index: true
    isRelatedPostsEnabled: true
    relatedPostsCount: 6

ui:
  theme: "system"
  tokens:
    colors:
      default: 'var(--aw-color-default)'
      muted: 'var(--aw-color-muted)'
      page: 'var(--aw-color-page)'
      primary: 'var(--aw-color-primary)'

image:
  imageSizes: [16, 32, 48, 64, 96, 128, 256, 384]
  deviceSizes: [640, 750, 828, 960, 1080, 1280, 1668, 1920, 2048, 2560, 3200, 3840, 4480, 5120, 6016]
  openGraph:
    defaultWidth: 1200
    defaultHeight: 626