site:
  name: nhavantuonglai
  site: 'https://nhavantuonglai.com'
  base: '/'
  trailingSlash: false

apps:
  blog:
    isEnabled: true
    postsPerPage: 20

    post:
      isEnabled: true
      permalink: 'article/%slug%'
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tags'
      robots:
        index: true

    isRelatedPostsEnabled: true
    relatedPostsCount: 12

ui:
  theme: 'system'

  tokens:
    default:
      colors:
        default: rgb(33 39 55)
        heading: rgb(248 243 240)
        muted: rgb(33 39 55 / 66%)
        bgPage: rgb(248 243 240)
        primary: rgb(255 114 94)
        secondary: rgb(255 114 94)
        accent: rgb(255 114 94)
    dark:
      fonts: {}
      colors:
        default: rgb(248 243 240)
        heading: rgb(33 39 55)
        muted: rgb(229 236 246 / 66%)
        bgPage: rgb(33 39 55)
        primary: rgb(255 114 94)
        secondary: rgb(255 114 94)
        accent: rgb(255 114 94)