site:
  name: nhavantuonglai
  site: 'https://nhavantuonglai.com'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId:

metadata:
  url: 'https://nhavantuonglai.com'

  title:
    default: nhavantuonglai
    template: '%s | nhavantuonglai'

  description: "nhavantuonglai là người viết lách chuyên nghiệp, tập trung viết dưới hình thức đoản văn, nghiên cứu và chia sẻ học thuật. Thể hiện vốn hiểu biết đời sống phong phú và kinh nghiệm viết vững vàng."

  robots:
    index: true
    follow: true

  og:
    site_name: nhavantuonglai
    images:
     url: 'https://data.nhavantuonglai.com/image/illustrations/cover-nhavantuonglai-com-0753.jpg'
     width: 600
     height: 407

    type: website

  image:
    url: 'trống, cần điền'
    secure_url: 'https://nhavantuonglai.com'
    type: 'image/jpeg'
    alt: 'trống, cần điền'

  twitter:
    image: 'trống, cần điền'
    title: 'trống, cần điền'
    description: 'trống, cần điền'
    twitter:card: 'trống, cần điền'
    handle: '@nhavantuonglai'
    site: '@nhavantuonglai'
    cardType: summary_large_image

i18n:
  language: vi
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 10

    post:
      isEnabled: true
      permalink: 'article/%slug%'
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'article'
      robots:
        index: true
    tag:
      isEnabled: true
      pathname: 'tags'
      robots:
        index: true

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

ui:
  theme: 'system'

  tokens:
    default:
      fonts:
        sans: InterVariable
        serif: InterVariable
        heading: InterVariable
      colors:
        default: rgb(33 39 55)
        heading: rgb(234 237 243)
        muted: rgb(33 39 55 / 66%)
        bgPage: rgb(234 237 243)
        primary: rgb(255 114 94)
        secondary: rgb(255 114 94)
        accent: rgb(255 114 94)
    dark:
      fonts: {}
      colors:
        default: rgb(234 237 243)
        heading: rgb(33 39 55)
        muted: rgb(229 236 246 / 66%)
        bgPage: rgb(33 39 55)
        primary: rgb(255 114 94)
        secondary: rgb(255 114 94)
        accent: rgb(255 114 94)