name: Update README with NPM Analytics

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch stats.md from python-npm-analytics
        run: |
          curl -o stats.md https://raw.githubusercontent.com/nhavantuonglai/python-npm-analytics/main/stats.md
      - name: Update README
        run: |
          sed -i '/<!-- npmjs-analytics-start -->/,/<!-- npmjs-analytics-end -->/{
            /<!-- npmjs-analytics-start -->/ r stats.md
            d
          }' README.md
      - name: Commit changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add README.md
          git commit -m "Update README with npm analytics table" || echo "No changes to commit"
          git push